### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by thunderbolt78** [kparichay/CryptoETF#4]
Hi,

iam running your script more than a year without any issues. but since few weeks i get this error. can you please takea look ?

`Executing Trades (LIVE) ->
Error:  !!!
Traceback (most recent call last):
  File "/root/etf_rebalance_a/execute_index_fund.py", line 283, in <module>
    main()
  File "/root/etf_rebalance_a/execute_index_fund.py", line 280, in main
    raise e
  File "/root/etf_rebalance_a/execute_index_fund.py", line 276, in main
    return exec(args)
  File "/root/etf_rebalance_a/execute_index_fund.py", line 124, in exec
    return fund.rebalance(**kwargs)
  File "/root/etf_rebalance_a/index_fund.py", line 205, in rebalance
    return self.reinvest(
  File "/root/etf_rebalance_a/index_fund.py", line 271, in reinvest
    return self.__updatePortfolio(
  File "/root/etf_rebalance_a/index_fund.py", line 145, in __updatePortfolio
    liquidated_amount = self.__liquidateTrades(liquidate_trades, live_run)
  File "/root/etf_rebalance_a/index_fund.py", line 52, in __liquidateTrades
    return self.__executeTrades(trades,
  File "/root/etf_rebalance_a/index_fund.py", line 47, in __executeTrades
    non_self_trades_amount = sum([tradeFunc(symbol[0], symbol[1], quant, live_run)
  File "/root/etf_rebalance_a/index_fund.py", line 47, in <listcomp>
    non_self_trades_amount = sum([tradeFunc(symbol[0], symbol[1], quant, live_run)
  File "/root/etf_rebalance_a/binance_client.py", line 254, in sellOrder
    return self.__placeOrder(symbol,
  File "/root/etf_rebalance_a/binance_client.py", line 192, in __placeOrder
    if quant < self.__getMinNotional(pair):
  File "/root/etf_rebalance_a/binance_client.py", line 173, in __getMinNotional
    return float(self.__getPairLotInfo(pair, "minNotional",
  File "/root/etf_rebalance_a/binance_client.py", line 169, in __getPairLotInfo
    assert len(min_info) == 1
AssertionError
`

**Comment by thunderbolt78** [comment]
hi, if i take a look into the log the script dont work since 19th april 2023. these are the changes

2023-04-18

    New endpoints for Spot Algo：
        POST /sapi/v1/algo/spot/newOrderTwap to support new order
        DELETE /sapi/v1/algo/spot/order to support cancel Algo order
        GET /sapi/v1/algo/spot/openOrders to support query Algo open orders
        GET /sapi/v1/algo/spot/historicalOrders to support query Algo historical orders
        GET /sapi/v1/algo/spot/subOrders to support query Algo sub orders for a specified algoId

please respond
